# 数据库的配置信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.104:3306/DZBD?useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis的配置信息
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  
server:
  port: 8080

